# Generated by Django 2.2 on 2019-06-07 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj_logs', '0004_auto_20190527_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='name',
            field=models.CharField(default='xdsc', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_logs.Topic'),
        ),
    ]
